branch-defaults:
  master:
    environment: habitat-api
    group_suffix: null
environment-defaults:
  habitat-api:
    branch: null
    repository: null
global:
  application_name: habitat-api
  branch: null
  default_ec2_keyname: habitat
  default_platform: Docker
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: habitat
  repository: null
  sc: git
  workspace_type: Application
